mybatis:
  typeAliasesPackage: org.lisy.student.entity
    mapperLocations: classpath:mapping/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j2ee
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/templates/
    suffix: .html
    cache: false